parameters:
    pzs.twig.wcf_extension.class: PzS\WCFCoreBundle\Twig\WCFCoreExtension
    language_manager.class: PzS\WCFCoreBundle\Service\Language\LanguageManager
    
services:
    pzs.twig.wcf_extension:
        class: %pzs.twig.wcf_extension.class%
        arguments: ["@language_manager"]
        tags:
            - { name: twig.extension }
    language_manager:
        class: "%language_manager.class%"