parameters:
    pzs.twig.wcf_extension.class: Pzs\WCFCoreBundle\Twig\WCFCoreExtension
    cache_service.class: Pzs\WCFCoreBundle\Service\Cache\CacheService
    cache_service.source: Pzs\WCFCoreBundle\Cache\Source\DiskCacheSource
    language_service.class: Pzs\WCFCoreBundle\Service\Language\LanguageService
    language_repository.class: Pzs\WCFCoreBundle\Repository\LanguageRepository
    language_repository.factory_argument: "PzsWCFCoreBundle:Language"
    language_category_repository.class: Pzs\WCFCoreBundle\Repository\LanguageCategoryRepository
    language_category_repository.factory_argument: "PzsWCFCoreBundle:LanguageCategory"
    
services:
    pzs.twig.wcf_extension:
        class: "%pzs.twig.wcf_extension.class%"
        arguments: 
            - "@language_service"
        tags:
            - { name: twig.extension }
    cache_service:
        class: "%cache_service.class%"
        source: "%cache_service.source%"
        arguments:
            - "@cache_service.source"
    language_service:
        class: "%language_service.class%"
        arguments: 
            - "@language_repository"
            - "@language_category_repository"
    language_repository:
        class: "%language_repository.class%"
        factory_service: doctrine.orm.entity_manager
        factory_method: "getRepository"
        arguments:
            - "@language_repository.factory_argument"
    language_category_repository:
        class: "%language_category_repository.class%"
        factory_service: doctrine.orm.entity_manager
        factory_method: "getRepository"
        arguments:
            - "@language_category_repository.factory_argument"
